<a href="https://colab.research.google.com/github/abdullahbilalawan/PytorchBasics/blob/master/Pytorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# libraries to import

import torch 
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

In [2]:
# creating a tensor


x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)






In [3]:
y = w*x +b

In [4]:
y

tensor(5., grad_fn=<AddBackward0>)

In [5]:
# back propagation

y.backward

<bound method Tensor.backward of tensor(5., grad_fn=<AddBackward0>)>

In [9]:
# tensor shapes

a = torch.randn(3,2)
b = torch.randn(3,1)

In [10]:
a

tensor([[ 1.5859,  0.3643],
        [-0.8372,  0.5924],
        [ 1.7341,  1.5375]])

In [11]:
# fully connected layer

layer  = nn.Linear(3,2)

In [13]:
x = torch.randn(10, 3)
y = torch.randn(10, 2)

# Build a fully connected layer.
linear = nn.Linear(3, 2)
print ('w: ', linear.weight)
print ('b: ', linear.bias)

# Build loss function and optimizer.
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

# Forward pass.
pred = linear(x)

# Compute loss.
loss = criterion(pred, y)
print('loss: ', loss.item())

w:  Parameter containing:
tensor([[-0.5172, -0.5746, -0.4154],
        [ 0.0176,  0.2771,  0.4181]], requires_grad=True)
b:  Parameter containing:
tensor([-0.3039,  0.5302], requires_grad=True)
loss:  1.6877124309539795
